name: 'Maven Action'
description: 'Install a specific version of Apache Maven and add it to the PATH'
author: 'hb0730'
inputs:
  maven-file:
    description: 'Path to the Maven archive to download'
    default: ''
  url:
    description: 'URL to download Maven from'
    default: ''
  maven-version:
    description: 'Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0'
    default: '3.8.2'
outputs:
  version:
    description: 'Installed maven version'
  path:
    description: 'Path to where maven environment has been installed (sam as $MAVEN_HOME)'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  color: 'purple'
  icon: 'play-circle'
